Placeholder snapshot for bazel crash.
Run on macOS:

./bazel test //test/scip/repos:shopify-api-ruby --config=dbg

Get an error:

java.lang.RuntimeException: Unrecoverable error while evaluating node 'UnshareableActionLookupData{actionLookupKey=ConfiguredTargetKey{label=//test/scip/repos:shopify-api-ruby, config=BuildConfigurationValue.Key[a0b0f51c82757f41f8c4b9bcfad394c044036ab831d46c88c4d210dee4476ea1]}, actionIndex=4}' (requested by nodes 'TestCompletionKey{configuredTargetKey=ConfiguredTargetKey{label=//test/scip/repos:shopify-api-ruby, config=BuildConfigurationValue.Key[a0b0f51c82757f41f8c4b9bcfad394c044036ab831d46c88c4d210dee4476ea1]}, topLevelArtifactContext=com.google.devtools.build.lib.analysis.TopLevelArtifactContext@90904c3b, exclusiveTesting=false}')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator.run(AbstractParallelEvaluator.java:674)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor.run(AbstractQueueVisitor.java:382)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: TEST_NAME=//test/scip/repos:shopify-api-ruby and TEST_NAME=shopify-api-ruby
        at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:210)
        at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:204)
        at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:146)